version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bugtracker-sql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    networks:
      - bugtracker-net
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:

networks:
  bugtracker-net:
